[env:seeed_xiao_esp32_c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyACM1
monitor_port = /dev/ttyACM1
lib_deps =
    h2zero/NimBLE-Arduino@^2.3.6
